version: "2"
services:
  fast-api:
    container_name: fast-api-practice
    restart: always
    build:
      context: .
      args:
        - EXTRA_REQUIREMENTS=requirements-dev.txt
    volumes:
      - ${PWD}:/app
    environment:
      - DB_HOSTNAME=${DB_HOSTNAME}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:13.1-alpine
    container_name: fast-api-postgres
    ports:
      - "54321:5432"
    environment:
      - VIRTUAL_HOST=fast-api-postgres.docker
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST_AUTH_METHOD=trust
